# Configuration Prometheus
# Auteur: FIENI Dannie Innocent Junior
# Formation: MCS 26.2 Cybersécurité & Cloud Computing - IPSSI Nice

# Configuration globale
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'todo-app-monitor'
    environment: 'development'

# Configuration Alertmanager (pour future configuration d'alerting)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Fichiers de règles (pour futures règles d'alerting)
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Configuration de collecte
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Node Exporter - Métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s
    metrics_path: '/metrics'

  # PostgreSQL Exporter - Métriques base de données
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Traefik métriques
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Application Flask métriques (si implémentées)
  - job_name: 'todo-api'
    static_configs:
      - targets: ['app:5000']
    scrape_interval: 30s
    metrics_path: '/metrics'
    scrape_timeout: 10s

